/**
 * This file was autogenerated from leafwhoosh.mp3 by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _leafwhoosh_h_
#define _leafwhoosh_h_
//---------------------------------------------------------------------------------
extern const unsigned char leafwhoosh[];
extern const int leafwhoosh_size;
//---------------------------------------------------------------------------------
#endif //_leafwhoosh_h_
//---------------------------------------------------------------------------------
